<div class="licence">
<span>Licence CC BY-NC-ND</span>
<span>Valérie Roy</span>
<span><img src="../media/ensmp-25-alpha.png" /></span>
</div>

In [1]:
import numpy as np

# accessing arrays

   - exactely like you **access** **python lists**
   - it returns a **view** on the underlying array
   - it does **not copy** the underlying array (for the sake of **memory efficient**)
   - **views** are different objects but they refer to the **same** one-dimensional segment   
   - when needed, **copy** with the *numpy.ndarray.copy*

## accessing the whole array

In [125]:
a = np.array(np.arange(1, 25)).reshape((2, 3, 4)) # 2 arrays of 5 x 6 matrix

In [126]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

*a* contains two **matrices** (axis 0)  
   - *3* **rows** (axis 1) and *4* **columns** (axis 2) 

## accessing the whole array by subscripts

on the **three** dimensions, we take
   - ':' all blocks
   - ':' all rows
   - ':' all columns

In [127]:
b = a[:, :, :]
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

*b* is **not** the **same** object as *a*, but they **share** the **same** underlying memory

In [128]:
b is a

False

In [129]:
b[0, 0, 0] = 1000 # we modify b
a[0, 0, 0]        # a is modified !


1000

## accessing sub-arrays

we access the **first** element of *axis 0*  i.e. the **first** matrix

In [130]:
a[0]

array([[1000,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

In [131]:
a[0].shape

(3, 4)

## accessing sub-arrays by subscripts

we access also the **first** matrix with: *0* for the first block, ':' for **all** rows and ':' for **all** columns

In [132]:
b = a[0, :, :]
b

array([[1000,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

In [133]:
b.shape

(3, 4)

the sub-array is a **view**, the **underlying** memory segments are the **same** piece of memory

In [134]:
b is a[0]

False

In [135]:
b[0][0] = 2000  # we modify b
a[0][0][0]      # it modifies a

2000

## modifying a sub-array

In [136]:
a

array([[[2000,    2,    3,    4],
        [   5,    6,    7,    8],
        [   9,   10,   11,   12]],

       [[  13,   14,   15,   16],
        [  17,   18,   19,   20],
        [  21,   22,   23,   24]]])

In [137]:
b = a[1]
print(b)
b[0] # b[0] is an array of length 4

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


array([13, 14, 15, 16])

In [138]:
# when you modify a slice, you must stay consistent with the sizes
b[0] = [130, 140, 150, 160]
b[0]

array([130, 140, 150, 160])

## modifying a sub-array changes the underlying memory

you have **modified** *b*, it has **modified** the **underlying** memory of *a*

In [139]:
a # is modified

array([[[2000,    2,    3,    4],
        [   5,    6,    7,    8],
        [   9,   10,   11,   12]],

       [[ 130,  140,  150,  160],
        [  17,   18,   19,   20],
        [  21,   22,   23,   24]]])

In [140]:
b # is modified

array([[130, 140, 150, 160],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24]])

we can modify the **whole** first matrix of *a*

In [141]:
x = np.arange(900, 912).reshape(3, 4)

print(x)

x.shape

[[900 901 902 903]
 [904 905 906 907]
 [908 909 910 911]]


(3, 4)

In [142]:
a[0] = x # we modify the first matrix
a

array([[[900, 901, 902, 903],
        [904, 905, 906, 907],
        [908, 909, 910, 911]],

       [[130, 140, 150, 160],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

## refering to the same *numpy.ndarray*

In [143]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
b = a

a is b

True

the two variables *a* and *b*, refer to the same **object**

True

In [145]:
a[0][0] = 999 # we modify a

In [146]:
b[0][0] # it modifies b

999

### several ways to access to the same element 

In [147]:
a = np.array(np.arange(1, 25)).reshape((2, 3, 4)) # 2 arrays of 5 x 6 matrix

In [148]:
a[0][0][0] # the first element of axis 2 (columns)
           # the first element of axis 1 (rows)
           # of the first element of axis 0 

1

In [149]:
a[0, 0, 0] # the same element

1

## assignment can truncate values

In [150]:
a.dtype

dtype('int64')

we try to put a **float** into a **64-bits integer**

In [151]:
a[0, 0, 0] = 999.90
a[0][0][0]

999

the value has been **truncated** to fit in a 64 bits integer

## slicing arrays

   - exactely like you **slice** **python lists**
   - it returns a **view** on the underlying array
   - it does **not copy** the underlying array (for the sake of **memory efficient**)
   - **views** are different objects but they refer to the **same** one-dimensional segment  
   - when needed, **copy** with the *numpy.ndarray.copy*

## basic slicing
   - **[from:to:step]** is done like python lists slicing

In [161]:
a = np.array(np.arange(1, 25)).reshape((2, 3, 4))

In [162]:
a[:, 0:2, 2:4]

array([[[ 3,  4],
        [ 7,  8]],

       [[15, 16],
        [19, 20]]])

':' all matrices  
*0:2* rows from index *0* to index *2* (excluded)  
*2:4* columns from index *2* to index *4* (excluded) 

## basic slicing with steps
   - **[from:to:step]** is done like python lists slicing

In [167]:
a = np.array(np.arange(1, 49)).reshape((6, 8))

In [168]:
a[0::2, 1::3] # one row over two, starting at index 0
              # one column over three, starting at column 1

array([[ 2,  5,  8],
       [18, 21, 24],
       [34, 37, 40]])